[package]
name = "sse-tester"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
env_logger = "0.11.8"
eventsource-client = "0.15.0"
futures = "0.3.31"
json = "0.12.4"
tokio = { version = "1.17.0", features = ["full", "time"] }
